name: AI Agent – Issue Listener

on:
  issues:
    types: [opened]
  pull_request:
  push:

jobs:
  acknowledge:
    runs-on: ubuntu-latest

    steps:
      - name: Acknowledge issue
        uses: actions/github-script@v7
        with:
          script: |
            const issueNumber = context.issue.number;
            const owner = context.repo.owner;
            const repo = context.repo.repo;

            await github.rest.issues.createComment({
              owner,
              repo,
              issue_number: issueNumber,
              body: "🟢 Задача принята. Агент начал обработку."
            });

  quality-gates:
    runs-on: ubuntu-latest
    if: github.event_name != 'issues'
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        working-directory: ai-platform
        run: pip install -r backend/requirements.txt

      - name: Ruff
        working-directory: ai-platform
        run: ruff check .

      - name: Pytest
        working-directory: ai-platform
        run: python -m pytest -q
